#!/usr/bin/env python3
"""Project model-comparison costs for the chat archive.

This script is intentionally local-first:
- model pricing comes from a checked-in catalog with verification date + source URLs
- archive token estimates are derived from the actual normalized chats and prompts
- reports are written under data/reports/ (gitignored)

If run-manifest files are supplied later, the script can compare heuristic estimates
with empirical sample costs from actual model runs.
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from typing import Any

import extract
import validate_extraction


RETROSPECT_ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = RETROSPECT_ROOT / "config" / "model_catalog.json"
REPORT_DIR = RETROSPECT_ROOT / "data" / "reports"
SAMPLE_DIR = RETROSPECT_ROOT / "data" / "samples"
GROUP_ORDER = ("extra_small", "smaller", "flagship", "wildcard")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Analyze model costs for retrospect")
    parser.add_argument(
        "--catalog",
        default=str(CATALOG_PATH),
        help="Path to the checked-in model catalog JSON",
    )
    parser.add_argument(
        "--sample-manifest",
        default=str(SAMPLE_DIR / "model-cost-minimal-sample.json"),
        help="Path to a sample manifest JSON generated by select_representative_sample.py",
    )
    parser.add_argument(
        "--run-manifest",
        dest="run_manifests",
        action="append",
        help="Optional extraction run manifest(s) to incorporate empirical sample costs",
    )
    parser.add_argument(
        "--output-stem",
        default="model-cost-analysis",
        help="Stem for report outputs under data/reports/",
    )
    return parser.parse_args()


def load_catalog(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def load_sample_manifest(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(
            f"Sample manifest not found: {path}. Run select_representative_sample.py first."
        )
    return json.loads(path.read_text(encoding="utf-8"))


def compute_prompt_totals(chat_paths: list[Path]) -> dict[str, Any]:
    per_pass = defaultdict(int)
    per_chat_total = 0
    for chat_path in chat_paths:
        doc = extract.parse_chat_document(chat_path)
        chat_total = 0
        for pass_id in validate_extraction.PASS_SCHEMAS:
            system_prompt, user_prompt = extract.render_prompt(pass_id, doc)
            tokens = extract.estimate_tokens(system_prompt) + extract.estimate_tokens(
                user_prompt
            )
            per_pass[pass_id] += tokens
            chat_total += tokens
        per_chat_total += chat_total
    return {
        "per_pass_prompt_tokens": dict(per_pass),
        "total_prompt_tokens": per_chat_total,
        "task_count": len(chat_paths) * len(validate_extraction.PASS_SCHEMAS),
        "heuristic_completion_tokens": sum(
            extract.DEFAULT_OUTPUT_TOKENS[pass_id] * len(chat_paths)
            for pass_id in validate_extraction.PASS_SCHEMAS
        ),
    }


def load_run_manifest(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def empirical_cost_overrides(run_manifests: list[Path]) -> dict[str, dict[str, Any]]:
    overrides = {}
    for path in run_manifests:
        manifest = load_run_manifest(path)
        model = manifest["model"]
        if manifest.get("chat_count", 0) <= 0 or manifest.get("task_count", 0) <= 0:
            continue
        overrides[model] = {
            "path": str(path),
            "chat_count": manifest["chat_count"],
            "task_count": manifest["task_count"],
            "actual_prompt_tokens": manifest.get("actual_prompt_tokens"),
            "actual_completion_tokens": manifest.get("actual_completion_tokens"),
            "reported_cost_total": manifest.get("reported_cost_total"),
        }
    return overrides


def money(value: float | None) -> str:
    if value is None:
        return "n/a"
    return f"${value:,.2f}"


def unit_cost(prompt_tokens: int, completion_tokens: int, model: dict[str, Any]) -> float:
    prompt_cost = (prompt_tokens / 1_000_000) * model["input_cost_per_million"]
    completion_cost = (completion_tokens / 1_000_000) * model["output_cost_per_million"]
    return prompt_cost + completion_cost


def build_projection_rows(
    models: list[dict[str, Any]],
    archive_totals: dict[str, Any],
    sample_totals: dict[str, Any],
    empirical: dict[str, dict[str, Any]],
) -> list[dict[str, Any]]:
    rows = []
    for model in models:
        row = dict(model)
        row["sample_cost_heuristic"] = unit_cost(
            sample_totals["total_prompt_tokens"],
            sample_totals["heuristic_completion_tokens"],
            model,
        )
        row["archive_cost_heuristic"] = unit_cost(
            archive_totals["total_prompt_tokens"],
            archive_totals["heuristic_completion_tokens"],
            model,
        )

        empirical_entry = empirical.get(model["resolved_id"])
        if empirical_entry and empirical_entry.get("actual_completion_tokens") is not None:
            actual_sample_cost = empirical_entry.get("reported_cost_total")
            row["sample_cost_empirical"] = actual_sample_cost

            avg_completion_per_task = (
                empirical_entry["actual_completion_tokens"] / empirical_entry["task_count"]
            )
            projected_completion_tokens = round(
                avg_completion_per_task * archive_totals["task_count"]
            )
            row["archive_cost_empirical"] = unit_cost(
                archive_totals["total_prompt_tokens"],
                projected_completion_tokens,
                model,
            )
            row["empirical_manifest"] = empirical_entry["path"]
        else:
            row["sample_cost_empirical"] = None
            row["archive_cost_empirical"] = None
            row["empirical_manifest"] = None

        rows.append(row)
    return rows


def mermaid_chart(title: str, rows: list[dict[str, Any]], field: str) -> str:
    if not rows:
        return ""
    labels = ", ".join(f'"{row["label"]}"' for row in rows)
    values = ", ".join(f"{row[field]:.3f}" for row in rows)
    max_value = max(row[field] for row in rows) if rows else 0
    return (
        "```mermaid\n"
        "xychart-beta\n"
        f'    title "{title}"\n'
        f"    x-axis [{labels}]\n"
        f'    y-axis "USD" 0 --> {max_value * 1.15:.3f}\n'
        f"    bar [{values}]\n"
        "```\n"
    )


def write_report(
    *,
    output_stem: str,
    catalog: dict[str, Any],
    sample_manifest: dict[str, Any],
    archive_chat_count: int,
    archive_totals: dict[str, Any],
    sample_totals: dict[str, Any],
    all_models: list[dict[str, Any]],
    active_rows: list[dict[str, Any]],
) -> Path:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORT_DIR / f"{output_stem}.md"

    grouped_rows: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in active_rows:
        grouped_rows[row["group"]].append(row)

    lines = [
        "# Retrospect Model Cost Analysis",
        "",
        f"- Verified pricing date: {catalog['verified_at']}",
        f"- Pricing source baseline: {catalog['verified_source']}",
        f"- Archive chat count: {archive_chat_count}",
        f"- Sample size: {sample_manifest['sample_size']}",
        "",
        "## Resolution Notes",
        "",
        "| Requested | Resolved | Status | Note |",
        "|---|---|---|---|",
    ]

    for model in all_models:
        resolved = model["resolved_id"] or "n/a"
        lines.append(
            f"| `{model['requested_id']}` | `{resolved}` | `{model['status']}` | {model['note']} |"
        )

    lines.extend(
        [
            "",
            "## Token Baselines",
            "",
            f"- Archive prompt tokens across all four passes: `{archive_totals['total_prompt_tokens']}`",
            f"- Archive heuristic completion tokens across all four passes: `{archive_totals['heuristic_completion_tokens']}`",
            f"- Sample prompt tokens across all four passes: `{sample_totals['total_prompt_tokens']}`",
            f"- Sample heuristic completion tokens across all four passes: `{sample_totals['heuristic_completion_tokens']}`",
            "",
            "Heuristic completion tokens use the extractor's current per-pass defaults, not measured sample outputs. Reasoning-token billing and provider-specific output behavior can move actual costs above or below these projections.",
            "",
        ]
    )

    for group in GROUP_ORDER:
        rows = grouped_rows.get(group, [])
        if not rows:
            continue
        group_title = group.replace("_", " ").title()
        lines.extend(
            [
                f"## {group_title} Group",
                "",
                "| Model | Input $/M | Output $/M | Sample Heuristic | Full Archive Heuristic | Sample Empirical | Full Archive Empirical |",
                "|---|---|---|---|---|---|---|",
            ]
        )
        for row in rows:
            lines.append(
                f"| `{row['resolved_id']}` | {row['input_cost_per_million']} | {row['output_cost_per_million']} | "
                f"{money(row['sample_cost_heuristic'])} | {money(row['archive_cost_heuristic'])} | "
                f"{money(row['sample_cost_empirical'])} | {money(row['archive_cost_empirical'])} |"
            )
        lines.extend(
            [
                "",
                mermaid_chart(
                    f"{group_title} Group: Full Archive Heuristic Cost",
                    rows,
                    "archive_cost_heuristic",
                ),
                mermaid_chart(
                    f"{group_title} Group: Sample Heuristic Cost",
                    rows,
                    "sample_cost_heuristic",
                ),
            ]
        )

    lines.extend(
        [
            "## Sample Run Commands",
            "",
            "From `retrospect/`:",
            "",
            "```bash",
        ]
    )
    sample_list = SAMPLE_DIR / "model-cost-minimal-sample.txt"
    for row in active_rows:
        lines.append(
            f"./.venv/bin/python scripts/extract.py --model {row['resolved_id']} --chat-list-file {sample_list}"
        )
    lines.extend(["```", ""])

    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path


def main() -> None:
    args = parse_args()
    catalog = load_catalog(Path(args.catalog))
    sample_manifest = load_sample_manifest(Path(args.sample_manifest))

    archive_chat_paths = sorted((RETROSPECT_ROOT / "data" / "chats").glob("*.md"))
    sample_chat_paths = [
        RETROSPECT_ROOT / item["relative_path"] for item in sample_manifest["selected_chats"]
    ]

    archive_totals = compute_prompt_totals(archive_chat_paths)
    sample_totals = compute_prompt_totals(sample_chat_paths)

    run_manifest_paths = [Path(item) for item in (args.run_manifests or [])]
    empirical = empirical_cost_overrides(run_manifest_paths)

    all_models = catalog["models"]
    active_models = [
        model
        for model in all_models
        if model["resolved_id"] is not None
        and model["input_cost_per_million"] is not None
        and model["output_cost_per_million"] is not None
    ]
    rows = build_projection_rows(active_models, archive_totals, sample_totals, empirical)

    report_path = write_report(
        output_stem=args.output_stem,
        catalog=catalog,
        sample_manifest=sample_manifest,
        archive_chat_count=len(archive_chat_paths),
        archive_totals=archive_totals,
        sample_totals=sample_totals,
        all_models=all_models,
        active_rows=rows,
    )

    print(f"Archive chats: {len(archive_chat_paths)}")
    print(f"Sample chats: {sample_manifest['sample_size']}")
    print(f"Report: {report_path}")

    print("\nTop heuristic full-archive projections:")
    for row in sorted(rows, key=lambda item: item["archive_cost_heuristic"]):
        print(
            f"  {row['resolved_id']:<35} "
            f"{money(row['archive_cost_heuristic'])} heuristic"
        )


if __name__ == "__main__":
    main()
